name: Test React App
on: [push, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: code
        uses: actions/checkout@v3
      - name: install node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: run Tests
        run: npm run test
