name: Deploy React App
permissions:
  contents: write
# on: [workflow_dispatch, push]
on:
  workflow_dispatch:
  # push:
  #   branches: [main, "hotfix-*", "feature/**"]
  #   path-ignores: [".github/workflows/*"]
  # pull_request:
  #   types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code
        uses: actions/checkout@v3
      - name: install node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: Build
        run: npm run build
        working-directory: react-app
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          branch: gh-pages
        env:
        ACCESS_TOKEN:${{ secrets.ACCESS_TOKEN}}
